# Generated by Django 4.0.3 on 2023-03-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_curriculum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='imgUrl',
            field=models.URLField(null=True),
        ),
    ]
