# Generated by Django 4.0.3 on 2023-03-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_alter_curriculum_user_practiceproblems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='user',
        ),
        migrations.RemoveField(
            model_name='practiceproblems',
            name='user',
        ),
    ]
