# Generated by Django 4.0.3 on 2023-03-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_remove_curriculum_user_remove_practiceproblems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.TextField(),
        ),
    ]
